### PR TITLE
enable kernel staging driver by default

### PR DESCRIPTION
**Pull request by yongli3**
HMC5843 kernel module is depending on CONFIG_STAGING,
after kernel upgrades, it is disabled in the defconfig,
enable it in the local sensors.cfg file

Fixes: IOTOS-1716

Signed-off-by: Yong Li yong.b.li@intel.com

### CODE REVIEW

**Comment by yongli3** [comment]
@jlaako @pohly  @peijiajames please help to review

**Comment by pohly** [comment]
Your commit doesn't explain the implications, so I can't decide whether this needs to be merged and what the risks are. Care to explain?

**Comment by yongli3** [comment]
@pohly this pr is used to fix iotos-1716. the hmc kernel modules are missing in current release

**Comment by pohly** [comment]
@yongli3 what are potential downsides of enabling staging, i.e. what are the risks?

**Comment by yongli3** [comment]
@pohly since we enabled the staging drivers in previous releases, compared with old versions, I do not think there are new risks. I can compare the kernel config difference later

**Comment by pohly** [comment]
Merging despite unrelated Edison test failure (test hardware down).

**Pull request merged**
