### PR TITLE
Add proximity sensor APDS9960 support

### PR DESCRIPTION
**Pull request by yongli3**
To add proximity sensors into Soletta iio node

Signed-off-by: Yong Li yong.b.li@intel.com

### CODE REVIEW

**Comment by yongli3** [comment]
@pohly @barbieri @neofang @jlaako please review. this PR is used for https://github.com/solettaproject/soletta/issues/1971

**Comment by barbieri** [comment]
+1

**Comment by pohly** [comment]
ok to test

**Comment by jlaako** [comment]
Seems to have some CI failures, @yongli3 please check.

**Comment by yongli3** [comment]
@jlaako my local build for Galileo is okay, I just updated the PR to trigger the CI again. It seems that the second CI is okay now

**Pull request merged**
