### PR TITLE
linux-yocto: sync with upstream meta-intel layer

### PR DESCRIPTION
**Pull request by jlaako**
Upstream meta-intel layer now contains most of the needed patches which
makes them conflict. Drop such patches and make the kernel build again
against meta-intel revision 7965dc814964a30e54542b1d5ef2029d565240bd.

Signed-off-by: Jussi Laako jussi.laako@linux.intel.com

### CODE REVIEW

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
@jlaako this fails on intel-quark because galileo2.cfg has

```
CONFIG_ACPI_CUSTOM_DSDT_FILE="DSDT.hex"
CONFIG_ACPI_CUSTOM_DSDT=y
```

Looks like this PR would have to be pushed together with the meta-intel update.

**Comment by jlaako** [comment]
Yes, this depends on the stated meta-intel master branch revision, so it should go in in sync with corresponding meta-intel update...

**Comment by mythi** [comment]
@jlaako This is OK to merge since 7965dc814964a30e54542b1d5ef2029d565240bd is queued in ostro-os PR

**Pull request merged**
