### PR TITLE
Remove kernel SRCREV overrides

### PR DESCRIPTION
**Pull request by jlaako**
Updates kernel version and SRCREV to match 4.4.8 kernel sync commit in
upstream linux-yocto repository.

Signed-off-by: Jussi Laako jussi.laako@linux.intel.com

### CODE REVIEW

**Comment by jlaako** [comment]
@ipuustin this updates the kernel to newer patch level

**Comment by jlaako** [comment]
Ping @ipuustin

**Comment by ipuustin** [comment]
There's now 4.4.9 in linux-yocto. Could we go directly there?

**Comment by jlaako** [comment]
Updated revisions to 4.4.9

**Pull request merged**
