### PR TITLE
linux-yocto: update version 4.4 support

### PR DESCRIPTION
**Pull request by jlaako**
Update linux-yocto version 4.4 bbappend to match meta-intel upstream
revision 3f637d34c917214378b838a359ca9fcacf49d9ee. Effectively dropping
number of Galileo related add-on patches that are now available in
upstream.

Signed-off-by: Jussi Laako jussi.laako@linux.intel.com

### CODE REVIEW

**Comment by mythi** [comment]
is the ambient capabilities change for Edison intented in this PR?

**Comment by okartau** [comment]
retest this please

**Comment by jlaako** [comment]
@mythi yes it is, because currently linux-yocto-edison.bbappend is symlink to linux-yocto-4.1.bbappend. That change allows us later to update that symlink to linux-yocto-4.4.bbappend and drop the linux-yocto-4.1.bbappend file altogether. Current 4.1 is still used for BeagleBone because meta-yocto-bsp layer has not been updated to use 4.4 for BBB yet, while meta-intel already switched to 4.4.

**Comment by mythi** [comment]
@jlaako +1

**Comment by jlaako** [comment]
@mythi merged, now the meta-intel can be updated too without build breakage...

**Pull request merged**
