### PR TITLE
Enable Atheros Bluetooth chip as kernel module

### PR DESCRIPTION
**Pull request by wzhen12**
Ostro kernel should support as much hw as possible.
Atheros Bluetooth chip is the common Bluetooth chip.
It should be supported in Ostro.

Signed-off-by: Wu Zheng wu.zheng@intel.com

### CODE REVIEW

**Comment by pohly** [comment]
@wzhen12 please check your group membership. It shouldn't be necessary to okay your PRs.
@kad where do we have documentation about this?

ok to test

**Comment by wzhen12** [comment]
According to the mail list of  "enable ath3k" in "Ostro dev" mail list, Ostro shold include as much hw as possible. Therefore, ath3k for bluetooth should be enabled in Ostro.

I will test it.

**Comment by jlaako** [comment]
@wzhen12 can you also check the other BT drivers that are not currently included and make a PR for those?

**Comment by wzhen12** [comment]
@jlaako  Okay, I will do it and test the other BT drivers.

**Pull request merged**
