### PR TITLE
meta-ostro-bsp: Update linux-yocto-4.4 revision for Galileo boards

### PR DESCRIPTION
**Pull request by yongli3**
Update the revision to include several Galileo GPIO related patches

Fixes: IOTOS-1365

Signed-off-by: Yong Li yong.b.li@intel.com

### CODE REVIEW

**Comment by yongli3** [comment]
@mythi @jlaako @neofang @peijiajames please help to review

**Comment by mythi** [comment]
@yongli3 please check if the latest meta-intel covers this

```
-SRCREV_meta-i586-nlp-32-intel-common = "770996a263e22562c81f48fde0f0dc647156abce"
-SRCREV_machine-i586-nlp-32-intel-common = "c43425f73287757a166d74464fddf1f5389c9f59"
+SRCREV_meta-i586-nlp-32-intel-common = "bcc65090840f51a6ac937297be5c22fe268d01ab"
+SRCREV_machine-i586-nlp-32-intel-common = "1a72cec834de2c80b5563f8afbeea7664fd5ee05"
```

**Comment by yongli3** [comment]
@mythi  the linux-yocto-4.4 commit 1a72cec834de2c80b5563f8afbeea7664fd5ee05 includes these gpio related patches

**Comment by jlaako** [comment]
@yongli3 I understand from your comment that this can be closed and we can pull the meta-intel HEAD and https://github.com/ostroproject/meta-ostro-bsp/pull/33 instead?

**Comment by yongli3** [comment]
@jlaako PR #33 only updates the HEAD for corei7. This one is used for quark platform.They are different

**Comment by jlaako** [comment]
@yongli3 PR #33 is to be used with meta-intel revision d519b9d8e53e1e4dd3494d8a3a8e3e531b2b9788 or newer, which has SRCREV 7a073202d4d47b5ffecf1e8f57b036f83b1fe2e0

Is that OK?

**Comment by yongli3** [comment]
@jlaako The problem is PR #33 does not change the latest SRCREV on i586(quark boards), it only changes the corei7. Below is the current kernel version:
Quark:linux-yocto                         :4.4.3+gitAUTOINC+770996a263_c43425f732-r0
corei7:linux-yocto                         :4.4.3+gitAUTOINC+770996a263_1a72cec834-r0

After apply PR #33, quark version is not changed, it still is c43425f732. 
Quark:linux-yocto                         :4.4.3+gitAUTOINC+770996a263_c43425f732-r0
Corei7: linux-yocto                         :4.4.3+gitAUTOINC+770996a263_076cc85486-r0

The SRCREV_machine_i586-nlp-32-intel-common should be added into PR #33, or change this file: meta-intel/common/recipes-kernel/linux/linux-yocto_4.4.bbappend

**Comment by jlaako** [comment]
@yongli3 I'm not talking about the kernel revision we currently have in meta-intel, PR #33 is meant to be merged together when pulling latest upstream meta-intel where quark linux-yocto is at 7a073202d4d47b5ffecf1e8f57b036f83b1fe2e0 that's why I was asking if that one is sufficient. PR#33 just forwards the i7 kernel to current HEAD of the upstream kernel repository for BXT patches.

So you need to look here:
http://git.yoctoproject.org/cgit/cgit.cgi/meta-intel/tree/common/recipes-kernel/linux/linux-yocto_4.4.bbappend
not at ostro-os repository.

**Comment by yongli3** [comment]
@jlaako okay, the latest meta-intel includes these gpio patches, it can replace this PR

**Comment by jlaako** [comment]
@yongli3 Thanks! I'll close this as the kernel gets updated when combo-layer is run next time.

**Comment by yongli3** [comment]
Thanks @jlaako !

**Pull request closed without merging**
