### PR TITLE
backport MMA7455 device driver for linux-yocto-4.4

### PR DESCRIPTION
**Pull request by yongli3**
The Accel sensor MMA7455 driver is missing in linux-yocto-4.4,
backport it to support more IIO sensors

Fixes: IOTOS-757/partial
Upstream-Status:Backport[https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=a84ef0d181d917125f1f16cffe53f84c19968969]

Signed-off-by: Yong Li yong.b.li@intel.com

### CODE REVIEW

**Comment by yongli3** [comment]
@mythi @jlaako  @peijiajames @lihaofd, please help to review

**Comment by mythi** [comment]
ok to test

**Comment by mythi** [comment]
@yongli3 Upstream-status info slightly problematic since this is backported from the iio tree. Do you know if this is submitted to mainline?

I'd propose to modify 'for kernel 4.4.3' to 'for linux-yocto-4.4'

**Comment by yongli3** [comment]
@mythi  I updated this PR to add quark support and modified the commit message, please review

**Comment by lihaofd** [comment]
@mythi , could you help to review the PR?

**Comment by mythi** [comment]
@lihaofd looks good to me but please check why CI fails. Something wrong with your meta-ostro-bsp fork?

**Comment by yongli3** [comment]
@mythi @lihaofd I re-based the PR, please check again

**Comment by lihaofd** [comment]
@mythi, CI build only failed on test_beagleboneblackFailed#285 and test_edisonFailed#2, which might have nothing to do with this PR. Is it OK to merge the PR now?

**Comment by mythi** [comment]
@lihaofd we'll take #13 first

**Comment by lihaofd** [comment]
#13 had been merged. @mythi, could you help to merge this PR?

**Comment by jlaako** [comment]
@lihaofd I'd like to have a test build after meta-intel update that is related to #13 to make sure there are no conflicts. It updates the 4.4 kernel...

**Pull request merged**
