### PR TITLE
backport several sensor device drivers for kernel 4.1

### PR DESCRIPTION
**Pull request by yongli3**
The Accel sensor MMA7455 and LIS2DH/MMA9553/BMA222E/BMA255/BMA280 driver are missing in kernel 4.1.15,
enable them to support more IIO sensors

Fixes: IOTOS-757/partial
Upstream-Status:Backport[https://git.kernel.org/cgit/linux/kernel/git/jic23/iio.git/commit/?id=a84ef0d181d917125f1f16cffe53f84c19968969]

Signed-off-by: Yong Li yong.b.li@intel.com

### CODE REVIEW

**Comment by lihaofd** [comment]
@mythi,@jlaako, could you help to review and merge the PR? Then QA can start to verify the IOTOS-757 on Ostro image, thanks!

**Comment by mythi** [comment]
@lihaofd @yongli3 we're moving to 4.4 shortly. Which of these are part of 4.4 (I saw 98125e5 is but how about the others)

**Comment by yongli3** [comment]
@mythi thanks for your comment, could you let me know the exact 4.4 version number and the schedule? When we can get the 4.4 image for QA testing? I checked the v4.4 tag in kernel.org, the other commits are not included in it. Is it possible to merge this PR now? And we can adjust them after upgraded to 4.4.

**Comment by yongli3** [comment]
@mythi  I did not find the linux-yocto-4.4/dev in the ostro-os, only the below:
linux-yocto                         :4.1.15+gitAUTOINC+46bb64d605_788dfc9859-r0

**Comment by jlaako** [comment]
@yongli3 You can set following in your local.conf to switch the kernel:
PREFERRED_PROVIDER_virtual/kernel = "linux-yocto-dev"

I'm working on recipe updates to prepare for 4.4 kernel, I should have an experimental PR for that today...

**Comment by yongli3** [comment]
Thanks @jlaako I modified the intel-corei7-64.conf file and start the linux-yocto-dev build. I found it is the 4.4-rc+ version, maybe not the latest version ?

**Comment by jlaako** [comment]
I propose to first make sure that https://github.com/ostroproject/meta-ostro-bsp/pull/6 is good and then rebase these things on that one...

**Comment by mythi** [comment]
Agree with @jlaako

**Comment by mythi** [comment]
@yongli3 please check the latest ostro-os master

**Comment by yongli3** [comment]
@mythi by saying "please check the latest ostro-os master", do you mean the kernel 4.4 PR is merged in, it is okay for me to re-base these patches?

**Comment by jlaako** [comment]
@yongli3 @mythi What do we do with this? Patches could be rebased on the new 4.1.

**Comment by yongli3** [comment]
@mythi @jlaako I have submitted another one for these patches #10. For this one, we can close it

**Pull request closed without merging**
