### PR TITLE
Use ostro-6lowpan package to configure the 802.15.4

### PR DESCRIPTION
**Pull request by yongli3**
ostro-6lowpan provides the related systemd service files to configure 802.15.4,
spi-quark-baord and spi-minnowmax-board can use it as a runtime recommend

Signed-off-by: Yong Li yong.b.li@intel.com

### CODE REVIEW

**Comment by yongli3** [comment]
As discussed in #12, I add the ostro-6lowpan package as a runtime dependence, This PR dependes on https://github.com/ostroproject/meta-ostro/pull/60

@wzhen12 @yangbox @mythi @jlaako @lihaofd @peijiajames please help to review

**Comment by mythi** [comment]
-1 

This is not a good idea after all. What this PR is doing is that it sets a kernel driver package to depend on some user-space scripts.

RRECOMMENDS can be used but we'd still need to add ostro-6lowpan in the images separately.

**Comment by yongli3** [comment]
@mythi I changed the REDPEND to RRECOMMENDS. How to add the ostro-6lowpan package into the image separately?  Add it into the meta-ostro/recipes-image/images/ostro-image.bb ?

**Comment by mythi** [comment]
Please cleanup the merge commits

**Comment by yongli3** [comment]
@mythi  I changed the "+=" to "=", please check again. Regarding the "cleanup the merge commits", do you mean I need to modify the current commit message?

**Comment by mythi** [comment]
"meta-ostro-bsp: " is redundant. It'll become "meta-ostro-bsp: meta-ostro-bsp: " in ostro-os.

**Comment by yongli3** [comment]
Thanks @mythi I removed the "meta-ostro-bsp:", please review

**Comment by pohly** [comment]
On Thu, 2016-03-31 at 05:32 -0700, Mikko Ylinen wrote:

> "meta-ostro-bsp: " is redundant. It'll become "meta-ostro-bsp:
> meta-ostro-bsp: " in ostro-os.

While it is indeed redundant, the scripts manipulating the commit are is
intelligent enough to not duplicate the layer name.

**Comment by jlaako** [comment]
@mythi OK to merge?

**Comment by mythi** [comment]
@jlaako yes, the commit itself is good. However, I noticed this was not tested by CI so let me trigger that.

ok to test

**Comment by jlaako** [comment]
@yongli3 Please check the CI failures...

**Comment by mythi** [comment]
@jlaako this PR needed the new master. expecting it's getting good after this build

**Comment by yongli3** [comment]
@mythi @jlaako I checked the CI failures, I found build is okay, but the test on Gigabyte failed. Do I need to modify this PR ?

**Comment by mythi** [comment]
The build is OK now.

**Pull request merged**
