### PR TITLE
linux-yocto-edison: updated kernel 3.10.17 -> 3.10.98.

### PR DESCRIPTION
**Pull request by ipuustin**
This fixes a number of security problems and removes the need for us to carry some extra patches.

### CODE REVIEW

**Comment by kad** [comment]
It would be good to preserve patch authorship.

**Comment by ipuustin** [comment]
@kad: please elaborate. Which patch you mean?

**Comment by kad** [comment]
edison-bsp/recipes-kernel/linux/files/0001-Backport-compiler-gcc.h-from-4.2-kernel.patch

**Comment by ipuustin** [comment]
Gcc5 support is now coming from upstream kernel. See patch https://github.com/01org/edison-linux/commit/42abc5125d0cd1abba9d21133010dcea1f3a0e8f. I just removed the local patch because it's no longer needed.

Or do you mean that in your opinion we should be the authors of the patch that adds gcc5 support and not use the upstream version?

**Comment by kad** [comment]
Yes, if we have patch file in our layer, it would be good to maintain From: or Author: line to indicate from where it came from. This PR not removing patch entirely, thus would be better to have in header of it information about origin.

**Comment by ipuustin** [comment]
No, this PR is removing the patch entirely. This is what it says in the git log:

```
diff --git a/meta-edison-bsp/recipes-kernel/linux/files/0001-Backport-compiler-gcc.h-from-4.2-kernel.patch b/meta-edison-bsp/recipes-kernel/linux/files/0001-Backport-compiler-gcc.h-from-4.2-kernel.patch
deleted file mode 100644
index 26ca0aa..0000000
```

Also if you go check the directory https://github.com/ipuustin/meta-ostro-bsp/tree/edison-3.10.98/meta-edison-bsp/recipes-kernel/linux/files , you won't find that file. Or am I now misunderstanding something?

**Comment by jlaako** [comment]
@kad that original patch was made by copying header files from newer kernel version to older one and generating a diff for that...

**Comment by kad** [comment]
Ah, sorry, my bad. Syntax highlight of the patch content still suggested that some pieces of it left.
So, yes, file got removed and you can ignore my comments. my bad.

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
+1

**Comment by jlaako** [comment]
I have not been able to test this because I'm unable to build images for Edison again. Image creation fails when attempting to run swupd tools.

**Comment by jlaako** [comment]
After https://github.com/01org/meta-intel-iot-security/pull/108 I was able to build and test the image.

**Pull request merged**
